version: '3.1'

services:

  web:
    volumes:
      - ./PilotSystem:/var/www/html/
      - /var/www/html/vendor/
      - /var/www/html/storage/
      - ./PilotSystem/storage/logs:/var/www/html/storage/logs
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public

  db:
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - my-datavolume:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  my-datavolume:
