version: '3.1'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
